package cli

import "fmt"

func PrintExtendedHelp() {
	fmt.Println("Myrai - Your Personal AI Assistant")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println("  myrai                          Run in server mode (default)")
	fmt.Println("  myrai --server                 Run in server mode")
	fmt.Println("  myrai --cli                    Run interactive CLI mode")
	fmt.Println("  myrai -m 'message'             Send one-shot message")
	fmt.Println()
	fmt.Println("Setup & Configuration:")
	fmt.Println("  myrai onboard                  Run setup wizard")
	fmt.Println("  myrai config get <key>         Get configuration value")
	fmt.Println("  myrai config set <key> <val>   Set configuration value")
	fmt.Println("  myrai config edit              Edit config in $EDITOR")
	fmt.Println("  myrai config path              Show config file path")
	fmt.Println()
	fmt.Println("Server Management:")
	fmt.Println("  myrai gateway run              Start server (foreground)")
	fmt.Println("  myrai gateway status           Show gateway configuration")
	fmt.Println("  myrai channels status          Show channel status")
	fmt.Println()
	fmt.Println("System & Diagnostics:")
	fmt.Println("  myrai status                   Show current status")
	fmt.Println("  myrai doctor                   Run diagnostics")
	fmt.Println("  myrai version                  Show version")
	fmt.Println()
	fmt.Println("Skills:")
	fmt.Println("  myrai skills                   List available skills")
	fmt.Println("  myrai skills info <skill>      Show skill details")
	fmt.Println()
	fmt.Println("Project Management:")
	fmt.Println("  myrai project new <name> <type>   Create new project")
	fmt.Println("  myrai project list                List all projects")
	fmt.Println("  myrai project switch <name>       Switch to project")
	fmt.Println("  myrai project archive <name>      Archive a project")
	fmt.Println("  myrai project delete <name>       Delete a project")
	fmt.Println()
	fmt.Println("Batch Processing:")
	fmt.Println("  myrai batch -i <file>             Process prompts from file")
	fmt.Println("  myrai batch -i in.txt -o out.json Process and save results")
	fmt.Println()
	fmt.Println("Persona Commands:")
	fmt.Println("  myrai persona            Show current AI identity")
	fmt.Println("  myrai persona edit       Edit AI identity")
	fmt.Println("  myrai persona show       Show full identity file")
	fmt.Println()
	fmt.Println("User Commands:")
	fmt.Println("  myrai user               Show your profile")
	fmt.Println("  myrai user edit          Edit your profile")
	fmt.Println("  myrai user show          Show full profile file")
	fmt.Println()
	fmt.Println("Flags:")
	fmt.Println("  --config <path>          Path to config file")
	fmt.Println("  --data <path>            Path to data directory")
	fmt.Println("  --help, -h               Show this help")
	fmt.Println("  --version, -v            Show version")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  myrai gateway run &                          # Start server in background")
	fmt.Println("  myrai -m \"What's the weather in KL?\"       # One-shot query")
	fmt.Println("  myrai doctor                                 # Check setup")
	fmt.Println()
}

func PrintProjectHelp() {
	fmt.Println("Project Management Commands:")
	fmt.Println()
	fmt.Println("  myrai project new <name> <type>    Create new project")
	fmt.Println("  myrai project list                 List all projects")
	fmt.Println("  myrai project switch <name>        Switch to project")
	fmt.Println("  myrai project archive <name>       Archive a project")
	fmt.Println("  myrai project delete <name>        Delete a project")
	fmt.Println()
	fmt.Println("Project Types:")
	fmt.Println("  coding     - Software development")
	fmt.Println("  writing    - Content creation")
	fmt.Println("  research   - Research projects")
	fmt.Println("  business   - Business projects")
}

func PrintBatchHelp() {
	fmt.Println("Batch Processing Commands:")
	fmt.Println()
	fmt.Println("  myrai batch -i <input> [-o <output>] [options]")
	fmt.Println()
	fmt.Println("Options:")
	fmt.Println("  -i, --input <file>       Input file (txt or jsonl)")
	fmt.Println("  -o, --output <file>      Output file (optional)")
	fmt.Println("  -c, --concurrency <n>    Max concurrent requests (default: 3)")
	fmt.Println("  -t, --timeout <sec>      Request timeout in seconds (default: 60)")
	fmt.Println("  --tier <3|4|5>           Use rate limits for Moonshot tier (optional)")
	fmt.Println("  -h, --help               Show this help")
	fmt.Println()
	fmt.Println("Input Formats:")
	fmt.Println("  Text file:  One prompt per line (comments with #)")
	fmt.Println("  JSONL file: {\"id\": \"...\", \"message\": \"...\"}")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  myrai batch -i prompts.txt")
	fmt.Println("  myrai batch -i prompts.jsonl -o results.json")
	fmt.Println("  myrai batch -i prompts.txt -c 5 -t 120")
	fmt.Println("  myrai batch -i big_file.jsonl --tier 3 -o results.json")
	fmt.Println()
	fmt.Println("Moonshot Tier Limits:")
	fmt.Println("  Tier 3: 200 concurrent, 5000 RPM, 3M TPM")
	fmt.Println("  Tier 4: 400 concurrent, 5000 RPM, 4M TPM")
	fmt.Println("  Tier 5: 1000 concurrent, 10000 RPM, 5M TPM")
}

func PrintConfigHelp() {
	fmt.Println("Config Commands:")
	fmt.Println()
	fmt.Println("  myrai config get <key>        Get configuration value")
	fmt.Println("  myrai config set <key> <val>  Set configuration value")
	fmt.Println("  myrai config edit             Open config in editor")
	fmt.Println("  myrai config path             Show config file path")
	fmt.Println("  myrai config show             Display full config")
	fmt.Println()
}

func PrintChannelsHelp() {
	fmt.Println("Channel Commands:")
	fmt.Println()
	fmt.Println("  myrai channels status           Show channel status")
	fmt.Println("  myrai channels enable <name>    Enable a channel")
	fmt.Println("  myrai channels disable <name>   Disable a channel")
	fmt.Println()
	fmt.Println("Available channels: telegram, discord")
}

func PrintGatewayHelp() {
	fmt.Println("Gateway Commands:")
	fmt.Println()
	fmt.Println("  myrai gateway run      Start the server (foreground)")
	fmt.Println("  myrai gateway status   Show gateway configuration")
	fmt.Println("  myrai gateway stop     Show how to stop the server")
	fmt.Println("  myrai gateway logs     Show logging information")
	fmt.Println()
	fmt.Println("Aliases: start = run")
}

func PrintInteractiveHelp() {
	fmt.Println()
	fmt.Println("Interactive Commands:")
	fmt.Println("  help, h     - Show this help")
	fmt.Println("  new, n      - Start new conversation")
	fmt.Println("  clear, cls  - Clear screen")
	fmt.Println("  exit, quit  - Exit the program")
	fmt.Println()
}
